[package]
name = "oas3-gen"
version.workspace = true
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "oas3-gen"
required-features = ["async"]

[features]
default = ["async", "quick-xml", "reqwest", "eventsource"]
async = ["dep:fmmap", "dep:tokio"]
reqwest = []
eventsource = ["reqwest"]
quick-xml = []

[dependencies]
any_ascii.workspace = true
anyhow.workspace = true
blake3.workspace = true
bon.workspace = true
cfg-if.workspace = true
chrono.workspace = true
clap.workspace = true
comfy-table.workspace = true
crossterm.workspace = true
cruet.workspace = true
fmmap = { workspace = true, optional = true }
http.workspace = true
indexmap.workspace = true
inflections.workspace = true
itertools.workspace = true
json-canon.workspace = true
mediatype.workspace = true
num-format.workspace = true
oas3.workspace = true
percent-encoding.workspace = true
petgraph.workspace = true
prettyplease.workspace = true
proc-macro2.workspace = true
quote.workspace = true
regex.workspace = true
serde_json.workspace = true
serde.workspace = true
string_cache.workspace = true
strum.workspace = true
syn.workspace = true
tokio = { workspace = true, optional = true }

[dev-dependencies]
axum.workspace = true
axum-core.workspace = true
oas3-gen-support.workspace = true
reqwest = { workspace = true, features = ["json", "multipart", "http2", "native-tls", "query", "stream"] }
serde_with.workspace = true
tempfile.workspace = true
uuid.workspace = true
validator = { workspace = true, features = ["derive"] }
